export const LOG_TYPE_COLORS: Record<string, string> = {
    ERROR: "plasmo:bg-red-500 plasmo:text-white",
    EMERGENCY: "plasmo:bg-red-700 plasmo:text-white",
    DEBUG: "plasmo:bg-gray-500 plasmo:text-white",
    AUDIT: "plasmo:bg-blue-500 plasmo:text-white",
    SYSTEM: "plasmo:bg-purple-500 plasmo:text-white",
};

export const LOCAL_STORAGE_KEY = "scriptLogViewerState";

export const SQL_KEYWORDS = new Set([
    "SELECT",
    "FROM",
    "WHERE",
    "AND",
    "OR",
    "NOT",
    "IN",
    "IS",
    "NULL",
    "AS",
    "JOIN",
    "INNER",
    "LEFT",
    "RIGHT",
    "OUTER",
    "FULL",
    "CROSS",
    "ON",
    "ORDER",
    "BY",
    "ASC",
    "DESC",
    "GROUP",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "INSERT",
    "INTO",
    "VALUES",
    "UPDATE",
    "SET",
    "DELETE",
    "CREATE",
    "DROP",
    "ALTER",
    "TABLE",
    "INDEX",
    "VIEW",
    "DISTINCT",
    "ALL",
    "UNION",
    "EXCEPT",
    "INTERSECT",
    "LIKE",
    "BETWEEN",
    "EXISTS",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "DUAL",
    "FETCH",
    "FIRST",
    "NEXT",
    "ROW",
    "ROWS",
    "ONLY",
    "WITH",
]);

export const SQL_FUNCTIONS = new Set([
    "CAST",
    "NULLIF",
    "COALESCE",
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "TO_CHAR",
    "TO_DATE",
    "SYSDATE",
    "NVL",
    "DECODE",
    "SUBSTR",
    "INSTR",
    "UPPER",
    "LOWER",
    "TRIM",
    "LENGTH",
    "ROUND",
    "TRUNC",
    "ABS",
    "MOD",
    "BUILTIN",
    "DF",
    "CUSTOMLIST",
    "CUSTOMRECORD",
    "NVL2",
    "CONCAT",
    "REPLACE",
    "LPAD",
    "RPAD",
    "LTRIM",
    "RTRIM",
    "INITCAP",
    "ASCII",
    "CHR",
    "FLOOR",
    "CEIL",
    "POWER",
    "SQRT",
    "SIGN",
    "GREATEST",
    "LEAST",
    "ADD_MONTHS",
    "MONTHS_BETWEEN",
    "LAST_DAY",
    "NEXT_DAY",
    "EXTRACT",
    "ROW_NUMBER",
    "RANK",
    "DENSE_RANK",
    "OVER",
    "PARTITION",
]);
