export const scriptLogMockData = [
    {
        id: "1",
        date: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        type: "ERROR",
        script_name: "Customer Sync Script",
        script_id: "123",
        title: "SSS_MISSING_REQD_ARGUMENT",
        detail: '{"message": "N/search.create: Missing a required argument: type", "stack": "at search.create (N/search) at processCustomers (customersync.js:45:12)"}',
        user: "System",
    },
    {
        id: "2",
        date: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        type: "DEBUG",
        script_name: "Sales Order Processing",
        script_id: "456",
        title: "Processing order batch",
        detail: "SELECT id, tranid, entity FROM transaction WHERE type = 'SalesOrd' AND status = 'pending'",
        user: "admin@company.com",
    },
    {
        id: "3",
        date: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        type: "AUDIT",
        script_name: "Inventory Update",
        script_id: "789",
        title: "Inventory levels updated",
        detail: '{"itemsUpdated": 150, "warehouseId": "WH001", "timestamp": "2024-01-15T10:30:00Z"}',
        user: "warehouse@company.com",
    },
    {
        id: "4",
        date: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
        type: "SYSTEM",
        script_name: "Scheduled Report Generator",
        script_id: "321",
        title: "Report generation started",
        detail: "Generating monthly sales report for period 2024-01",
        user: "System",
    },
    {
        id: "5",
        date: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        type: "EMERGENCY",
        script_name: "Payment Processing",
        script_id: "654",
        title: "Critical: Payment gateway timeout",
        detail: '{"error": "GATEWAY_TIMEOUT", "transactionId": "TXN-2024-001234", "amount": 5499.99, "currency": "USD", "retryCount": 3}',
        user: "System",
    },
    {
        id: "6",
        date: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        type: "DEBUG",
        script_name: "Customer Sync Script",
        script_id: "123",
        title: "Customer record processed",
        detail: "Successfully synced customer ID: 12345 with external CRM",
        user: "integration@company.com",
    },
    {
        id: "7",
        date: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
        type: "ERROR",
        script_name: "Email Campaign Script",
        script_id: "987",
        title: "SSS_USAGE_LIMIT_EXCEEDED",
        detail: '{"usageType": "EMAIL", "currentUsage": 1000, "limit": 1000, "script": "emailcampaign.js"}',
        user: "marketing@company.com",
    },
    {
        id: "8",
        date: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
        type: "AUDIT",
        script_name: "User Provisioning",
        script_id: "147",
        title: "New user created",
        detail: '{"userId": "emp_00456", "email": "newuser@company.com", "role": "Sales Representative", "subsidiary": "US Operations"}',
        user: "hr@company.com",
    },
    {
        id: "9",
        date: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        type: "DEBUG",
        script_name: "Data Migration Script",
        script_id: "258",
        title: "Batch processing complete",
        detail: "SELECT * FROM customrecord_legacy_data WHERE migrated = 'F' AND ROWNUM <= 500",
        user: "admin@company.com",
    },
    {
        id: "10",
        date: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
        type: "SYSTEM",
        script_name: "Cleanup Script",
        script_id: "369",
        title: "Temporary files purged",
        detail: '{"filesDeleted": 47, "spaceReclaimed": "2.3GB", "folder": "/temp/exports"}',
        user: "System",
    },
];

export const scriptOptions = [
    { value: "123", label: "Customer Sync Script" },
    { value: "456", label: "Sales Order Processing" },
    { value: "789", label: "Inventory Update" },
    { value: "321", label: "Scheduled Report Generator" },
    { value: "654", label: "Payment Processing" },
    { value: "987", label: "Email Campaign Script" },
    { value: "147", label: "User Provisioning" },
    { value: "258", label: "Data Migration Script" },
    { value: "369", label: "Cleanup Script" },
];

export const logTypeOptions = [
    { value: "ERROR", label: "Error" },
    { value: "EMERGENCY", label: "Emergency" },
    { value: "DEBUG", label: "Debug" },
    { value: "AUDIT", label: "Audit" },
    { value: "SYSTEM", label: "System" },
];
